# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Ax"
license = "MIT"
licenselink = "https://github.com/axross/axross.io/blob/master/LICENSE.md"
description = ""
homepage = "http://axross.io/"
tags = []
features = []
min_version = 0.19

[author]
  name = "axross"
  homepage = "http://axross.io"
